pages:
  - page_name: Home
    icon: 🏠
    script_path: streamlit_app.py
    layout: wide  # By default, layout is 'centered' for all pages
sections:
  - name: Utility Apps
    icon: ⭐
    pages:
      - page_name: Example One
        icon: 🤠
        date_added: 2022-07-04  # If younger than a month, the page name will be augmented with a neat :new: emoji!
      - page_name: Custom name!  # Explicit naming here overwrites the name inferred from script_path
        icon: ⚡
        script_path: pages/example_two.py
  - name: More Apps
    icon: 💻
    pages:
      - page_name: Example three
        icon: 🦇
      - page_name: Old App
        icon: 💀
        visible: false  # This app will not appear in the menu!
